// <auto-generated />
using System;
using BookFilterAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookFilterAPI.Migrations
{
    [DbContext(typeof(BookFilterDbContext))]
    [Migration("20240920091511_hello")]
    partial class hello
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookFilterAPI.Models.Domain.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("430728ca-12b1-424f-850c-26172cddba73"),
                            Bio = "Bio of New Author 1.",
                            Birthdate = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "New Author 1",
                            ProfileImageUrl = "https://example.com/images/new_author_1.jpg"
                        },
                        new
                        {
                            Id = new Guid("6d141d6f-f24a-4bdd-90fc-fd03f67fb5ae"),
                            Bio = "Bio of New Author 2.",
                            Birthdate = new DateTime(1985, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "New Author 2",
                            ProfileImageUrl = "https://example.com/images/new_author_2.jpg"
                        },
                        new
                        {
                            Id = new Guid("67df8576-936e-4028-baa2-621b4411aa5e"),
                            Bio = "British author, best known for the Harry Potter series.",
                            Birthdate = new DateTime(1965, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "J.K. Rowling",
                            ProfileImageUrl = "https://example.com/images/jk_rowling.jpg"
                        },
                        new
                        {
                            Id = new Guid("cedafaee-281d-4495-b06e-2fa51bb90561"),
                            Bio = "American author, known for the 'A Song of Ice and Fire' series.",
                            Birthdate = new DateTime(1948, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "George R.R. Martin",
                            ProfileImageUrl = "https://example.com/images/george_rr_martin.jpg"
                        });
                });

            modelBuilder.Entity("BookFilterAPI.Models.Domain.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookSizeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("BookSizeId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("79ce6d52-2106-4a0e-b3a0-a31b59faa500"),
                            AuthorId = new Guid("430728ca-12b1-424f-850c-26172cddba73"),
                            BookSizeId = new Guid("9de96b83-eedb-4ee9-beaf-3498f5c38cc0"),
                            CoverImageUrl = "https://example.com/images/new_book_1.jpg",
                            Description = "Description for New Book 1.",
                            PublicationDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "New Book 1"
                        },
                        new
                        {
                            Id = new Guid("97ac36c3-f3ca-4a8e-9e37-f39a3124fc85"),
                            AuthorId = new Guid("6d141d6f-f24a-4bdd-90fc-fd03f67fb5ae"),
                            BookSizeId = new Guid("3038e735-fcbb-4daf-9753-23b040e00870"),
                            CoverImageUrl = "https://example.com/images/new_book_2.jpg",
                            Description = "Description for New Book 2.",
                            PublicationDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "New Book 2"
                        },
                        new
                        {
                            Id = new Guid("c9c18cf3-132b-40ef-97d6-57a9cdd45364"),
                            AuthorId = new Guid("67df8576-936e-4028-baa2-621b4411aa5e"),
                            BookSizeId = new Guid("4e2665d0-400c-44da-a3ca-fb874d7fac96"),
                            CoverImageUrl = "https://example.com/images/harry_potter_1.jpg",
                            Description = "First book in the Harry Potter series.",
                            PublicationDate = new DateTime(1997, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Harry Potter and the Philosopher's Stone"
                        },
                        new
                        {
                            Id = new Guid("aec57b56-d394-4b79-94ef-2e08ecfc288a"),
                            AuthorId = new Guid("cedafaee-281d-4495-b06e-2fa51bb90561"),
                            BookSizeId = new Guid("23dd92c0-f194-45d5-b143-d0227d399d73"),
                            CoverImageUrl = "https://example.com/images/game_of_thrones.jpg",
                            Description = "First book in the A Song of Ice and Fire series.",
                            PublicationDate = new DateTime(1996, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "A Game of Thrones"
                        });
                });

            modelBuilder.Entity("BookFilterAPI.Models.Domain.BookSize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BookSizes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9de96b83-eedb-4ee9-beaf-3498f5c38cc0"),
                            Size = "Extra Small"
                        },
                        new
                        {
                            Id = new Guid("3038e735-fcbb-4daf-9753-23b040e00870"),
                            Size = "Extra Large"
                        },
                        new
                        {
                            Id = new Guid("a5942dfe-ac0d-41c3-af83-04eabce51364"),
                            Size = "Small"
                        },
                        new
                        {
                            Id = new Guid("4e2665d0-400c-44da-a3ca-fb874d7fac96"),
                            Size = "Medium"
                        },
                        new
                        {
                            Id = new Guid("23dd92c0-f194-45d5-b143-d0227d399d73"),
                            Size = "Large"
                        });
                });

            modelBuilder.Entity("BookFilterAPI.Models.Domain.Book", b =>
                {
                    b.HasOne("BookFilterAPI.Models.Domain.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookFilterAPI.Models.Domain.BookSize", "BookSize")
                        .WithMany()
                        .HasForeignKey("BookSizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("BookSize");
                });
#pragma warning restore 612, 618
        }
    }
}
