// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PackageResortAPI.Data;

namespace PackageResortAPI.Migrations
{
    [DbContext(typeof(PackageResortDbContext))]
    partial class PackageResortDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PackageResortAPI.Models.Domain.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityName = "Los Angeles",
                            StateId = 1
                        },
                        new
                        {
                            Id = 2,
                            CityName = "Bangalore",
                            StateId = 2
                        });
                });

            modelBuilder.Entity("PackageResortAPI.Models.Domain.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryName = "USA"
                        },
                        new
                        {
                            Id = 2,
                            CountryName = "India"
                        });
                });

            modelBuilder.Entity("PackageResortAPI.Models.Domain.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Summer Vacation",
                            Price = 1200.50m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Winter Getaway",
                            Price = 900.00m
                        });
                });

            modelBuilder.Entity("PackageResortAPI.Models.Domain.PackageCity", b =>
                {
                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.HasKey("PackageId", "CityId");

                    b.HasIndex("CityId");

                    b.ToTable("PackageCities");

                    b.HasData(
                        new
                        {
                            PackageId = 1,
                            CityId = 1
                        },
                        new
                        {
                            PackageId = 1,
                            CityId = 2
                        },
                        new
                        {
                            PackageId = 2,
                            CityId = 2
                        });
                });

            modelBuilder.Entity("PackageResortAPI.Models.Domain.PackageResort", b =>
                {
                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<int>("ResortId")
                        .HasColumnType("int");

                    b.HasKey("PackageId", "ResortId");

                    b.HasIndex("ResortId");

                    b.ToTable("PackageResorts");

                    b.HasData(
                        new
                        {
                            PackageId = 1,
                            ResortId = 1
                        },
                        new
                        {
                            PackageId = 1,
                            ResortId = 2
                        },
                        new
                        {
                            PackageId = 2,
                            ResortId = 2
                        });
                });

            modelBuilder.Entity("PackageResortAPI.Models.Domain.Resort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("ResortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Resorts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            ResortName = "Beach Resort"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 2,
                            ResortName = "Mountain Resort"
                        });
                });

            modelBuilder.Entity("PackageResortAPI.Models.Domain.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("StateName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            StateName = "California"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 2,
                            StateName = "Karnataka"
                        });
                });

            modelBuilder.Entity("PackageResortAPI.Models.Domain.City", b =>
                {
                    b.HasOne("PackageResortAPI.Models.Domain.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("PackageResortAPI.Models.Domain.PackageCity", b =>
                {
                    b.HasOne("PackageResortAPI.Models.Domain.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PackageResortAPI.Models.Domain.Package", "Package")
                        .WithMany("PackageCities")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("PackageResortAPI.Models.Domain.PackageResort", b =>
                {
                    b.HasOne("PackageResortAPI.Models.Domain.Package", "Package")
                        .WithMany("PackageResorts")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PackageResortAPI.Models.Domain.Resort", "Resort")
                        .WithMany("PackageResorts")
                        .HasForeignKey("ResortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("Resort");
                });

            modelBuilder.Entity("PackageResortAPI.Models.Domain.Resort", b =>
                {
                    b.HasOne("PackageResortAPI.Models.Domain.City", "City")
                        .WithMany("Resorts")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("PackageResortAPI.Models.Domain.State", b =>
                {
                    b.HasOne("PackageResortAPI.Models.Domain.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("PackageResortAPI.Models.Domain.City", b =>
                {
                    b.Navigation("Resorts");
                });

            modelBuilder.Entity("PackageResortAPI.Models.Domain.Country", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("PackageResortAPI.Models.Domain.Package", b =>
                {
                    b.Navigation("PackageCities");

                    b.Navigation("PackageResorts");
                });

            modelBuilder.Entity("PackageResortAPI.Models.Domain.Resort", b =>
                {
                    b.Navigation("PackageResorts");
                });

            modelBuilder.Entity("PackageResortAPI.Models.Domain.State", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
