// <auto-generated />
using System;
using EmployeeAPIException.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeAPIException.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20240917073159_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("EmployeeAPIException.Models.Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("38dec2ee-1518-4e24-b0a9-89daa1146b64"),
                            Email = "john.doe@example.com",
                            MobileNumber = "1234567890",
                            Name = "John Doe",
                            Password = "password123",
                            Salary = 50000
                        },
                        new
                        {
                            Id = new Guid("385cd245-7530-4d45-840c-c7b1450e2c77"),
                            Email = "jane.smith@example.com",
                            MobileNumber = "0987654321",
                            Name = "Jane Smith",
                            Password = "password123",
                            Salary = 60000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
