// <auto-generated />
using System;
using EmployeeAPIJWT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeAPIJWT.Migrations
{
    [DbContext(typeof(EmployeeJWTDbContext))]
    [Migration("20240917121618_usertabledataseeded")]
    partial class usertabledataseeded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeeAPIJWT.Models.Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6b126ccd-734f-4705-8979-ba669713b919"),
                            Email = "john.doe@example.com",
                            MobileNumber = "1234567890",
                            Name = "John Doe",
                            Password = "password123",
                            Salary = 50000
                        },
                        new
                        {
                            Id = new Guid("f452b741-c1c3-4ede-9e54-73ff1f547e81"),
                            Email = "jane.smith@example.com",
                            MobileNumber = "0987654321",
                            Name = "Jane Smith",
                            Password = "password123",
                            Salary = 60000
                        });
                });

            modelBuilder.Entity("EmployeeAPIJWT.Models.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b682994d-68e9-4b3c-ae2c-348bc9e0405e"),
                            PasswordHash = "admin123",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("d6f7527f-0a25-40c8-8d47-f9d3d1e70b6e"),
                            PasswordHash = "user123",
                            Role = "User",
                            Username = "user1"
                        },
                        new
                        {
                            Id = new Guid("36451d92-3678-405d-a1b5-43a0b98d3705"),
                            PasswordHash = "user234",
                            Role = "User",
                            Username = "user2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
