// <auto-generated />
using System;
using EmployeeAPIJWT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeAPIJWT.Migrations
{
    [DbContext(typeof(EmployeeJWTDbContext))]
    [Migration("20240917093845_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("EmployeeAPIJWT.Models.Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3555589e-0f30-44de-a1e7-64fb8633afbc"),
                            Email = "john.doe@example.com",
                            MobileNumber = "1234567890",
                            Name = "John Doe",
                            Password = "password123",
                            Salary = 50000
                        },
                        new
                        {
                            Id = new Guid("d2d121a5-cebc-499e-bf5f-58281258211b"),
                            Email = "jane.smith@example.com",
                            MobileNumber = "0987654321",
                            Name = "Jane Smith",
                            Password = "password123",
                            Salary = 60000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
